make data hashable
lingpy/linse pull request #25
Opened 2023-11-30 13:26 UTC by LinguList

It is crucial in many situations to be able to hash a typed sequence, so this code provides, hopefully, all we need. Now, a typedsequence can also function as a key in a dictionary.

2023-11-30 13:35 UTC, xrotwang requested changes
We also need tests :)

2023-11-30 13:35 UTC, xrotwang commented on src/linse/typedsequence.py
> +    def __eq__(self):
That doesn't look right. The signature ought to be `def __eq__(self, other)`.

2023-11-30 15:17 UTC, LinguList commented
Yes, I found in fact that we must add more tests, I'll try and add them 
later!

2023-12-01 10:14 UTC, LinguList commented
Problems should be addressed now. The modification also fixes a problem resulting from appending something to a word, which resulted in not appending something tot he morphemes before. This is in my opinion fixed now.

2023-12-01 10:17 UTC, xrotwang commented
One question: Do we need a custom `__eq__` implementation? Isn't comparing the underlying sequences ok (or better)?

2023-12-01 10:20 UTC, LinguList commented
The eq-function reduces to the string representation, but I consider this as a feature rather than a problem. First, the string representation in CSV and other formats will be anyway the most clear representation of a word or a list of integers. Second, we cannot hash a word if we do not define an eq in this way (at least it throws errors and I read one must make sure to be consistent with eq when defining a hash).

2023-12-01 10:20 UTC, LinguList commented
It also means -- which I consider a feature -- that one can populare a dictionary with words in Python and later access words by their string representation.

2023-12-01 10:22 UTC, LinguList commented
Minimal example:

```python
w = Word("a + b")
d = {w: 1}
d["a + b"]
```
This yields a key error if we do not default to string representation when comparing in eq.

2023-12-01 10:26 UTC, xrotwang commented
I've just seen the test, that uses a literal string to retrieve something from a dictionary. I consider this a mis-feature, though. It's basically circumventing - and actually preventing - any useful type checking. E.g. the type hint for a dictionary keyed by `Word`s would now need to be `typing.Dict[typing.Union[str, Word], ...]` rather than just `typing.Dict[Word, ...]`.

I just fixed the failing test (after removing the `__eq__` method) by wrapping the literal string into `Word(...)`.

Having objects of one type behave like a different type in some circumstances does not only confuse a type checker. So I'd opt to remove it.

2023-12-01 10:29 UTC, LinguList commented
You are right. It is also not a real problem to populate a dictionary with strings. We could then even get rid of the hash itself.

2023-12-01 10:31 UTC, xrotwang commented
> Minimal example:
> 
> ```python
> w = Word("a + b")
> d = {w: 1}
> d["a + b"]
> ```
> 
> This yields a key error if we do not default to string representation when comparing in eq.

But this works:
```
>>> d[Word("a + b")]
```
and seems simple enough to me. I find the following weirder:
```python
>>> from linse.typedsequence import Word
>>> w = Word('a + b')
>>> 'a + b' == w
False
>>> 'a + b'.morphemes == w.morphemes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'morphemes'
```

2023-12-01 10:34 UTC, xrotwang commented
> You are right. It is also not a real problem to populate a dictionary with strings. We could then even get rid of the hash itself.

Making the thing hashable might be useful, see
```python
>>> {Word('a + b'), Word('a + c'), Word('a + b')}
{'a + c', 'a + b'}
```

2023-12-01 10:44 UTC, xrotwang approved these changes

2023-12-01 10:44 UTC, merged

2023-12-01 10:59 UTC, LinguList commented
Yes! I thought of dictionaries for now, but the SET feature is very cool for our purpose, even more important.